from CvGenerator import getFeatures
from CvObservations import getObservations


str1 = "Garth Blacksmith looked at the tiny newspaper in his hands and felt surprised.He walked over to the window and reflected on his urban surroundings. He had always loved deserted Exeter with its outrageous, open oceans. It was a place that encouraged his tendency to feel surprised.Then he saw something in the distance, or rather someone. It was the figure of Joshua Thornton. Joshua was a sympathetic coward with red moles and short lips.Garth gulped. He glanced at his own reflection. He was an optimistic, clumsy, tea drinker with ruddy moles and skinny lips. His friends saw him as an alert, abundant author. Once, he had even rescued a big owl from a burning building.But not even an optimistic person who had once rescued a big owl from a burning building, was prepared for what Joshua had in store today.The drizzle rained like shouting aardvarks, making Garth barmy.As Garth stepped outside and Joshua came closer, he could see the inexpensive glint in his eye.Joshua gazed with the affection of 8629 brutal pong pigeons. He said, in hushed tones, I love you and I want some more Twitter followers. Garth looked back, even more barmy and still fingering the tiny newspaper. Joshua, get out of my house, he replied.They looked at each other with worried feelings, like two pong, panicky puppies dancing at a very sweet bar mitzvah, which had trance music playing in the background and two down to earth uncles bopping to the beat.Garth studied Joshua's red moles and short lips. Eventually, he took a deep breath. I'm sorry, began Garth in apologetic tones, but I don't feel the same way, and I never will. I just don't love you Joshua. Joshua looked relaxed, his emotions raw like a gleaming, green guillotine."

str2 = "Chris Blunder had always loved snooty Madrid with its blue-eyed, big beaches. It was a place where he felt delighted.He was a stable, helpful, squash drinker with pink hands and pink thighs. His friends saw him as a dead, dirty dolphin. Once, he had even saved a quick chicken that was stuck in a drain. That's the sort of man he was. Chris walked over to the window and reflected on his cold surroundings. The sun shone like skipping flamingos. Then he saw something in the distance, or rather someone. It was the figure of Jenny Walker. Jenny was a mean knight with blonde hands and curvaceous thighs. Chris gulped. He was not prepared for Jenny.As Chris stepped outside and Jenny came closer, he could see the substantial glint in her eye.Look Chris, growled Jenny, with a scheming glare that reminded Chris of mean kittens. It's not that I don't love you, but I want a resolution. You owe me 1355 euros. Chris looked back, even more afraid and still fingering the enchanted book. Jenny, I admire your eyebrows, he replied. They looked at each other with surprised feelings, like two famous, fast flamingos sitting at a very stable snow storm, which had drum and bass music playing in the background and two hopeful uncles singing to the beat. Chris regarded Jenny's blonde hands and curvaceous thighs. I don't have the funds ... he lied. Jenny glared. Do you want me to shove that enchanted book where the sun don't shine? Chris promptly remembered his stable and helpful values. Actually, I do have the funds, he admitted. He reached into his pockets. Here's what I owe you."

str3 = "a a a b b c c c c"
str4 = "lol"

# TODO: add feature like n most freq tokens or singletons or other similarity methods

contextVectorHash1 = getFeatures(str1, str2, 2)
contextVectorHash2 = getFeatures(str2, str1, 2)
getObservations(contextVectorHash1, contextVectorHash2)